services:
  velocity:
    image: itzg/minecraft-server:${JAVA_VER}
    user: ${UID}:${GID}
    container_name: velocity
    env_file: ./env_velocity
    ports:
      - 25565:25565
    volumes:
      - ./proxy/velocity:/velocity
      - ./proxy/data:/data
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 5s
      retries: 20
    networks:
      - mc-backend
    restart: always
    depends_on: []
  mc:
    image: itzg/minecraft-server:${JAVA_VER}
    user: ${UID}:${GID}
    container_name: minecraft
    env_file: ./env_minecraft
    volumes:
      - ./data:/data
      - ./data/plugins:/plugins
    stdin_open: true
    tty: true
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 5s
      retries: 20
    networks:
      - mc-backend
    restart: always
    depends_on:
      velocity:
        condition: service_healty
volumes:
  data: {}
networks:
  mc-backend:
    external: true
x-dockge:
  urls:
    - play.vrl.sh
