version: "3.8"
services:
  baserow:
    restart: always
    container_name: baserow
    image: baserow/baserow:${BASEROW_VERSION:-1.22.1}
    user: ${UGID:-1000:100}
    env_file: ./.env
    networks:
      - proxy
    labels:
      - null
    ports:
      - ${WEBPORT:-3001}:80
    volumes:
      - ${DATA_PATH:-./data}:/baserow/data
volumes:
  baserow_data: null
networks:
  proxy:
    external: true
