version: "3.3"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:${KUMA_VERSION:-latest}
    container_name: uptime-kuma
    restart: always
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
volumes:
  uptime-kuma: {}
networks:
  proxy:
    external: true
